// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7pdYM0mWnpEtI9hNfXHHGeqZAek0UXPE',
    appId: '1:611184420790:android:72f54f689d84d85b914317',
    messagingSenderId: '611184420790',
    projectId: 'inspection-wv',
    storageBucket: 'inspection-wv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB3FdOs18xh0-AtsjCPjD581oguHEN_mk',
    appId: '1:611184420790:ios:0deb5e4faaf2ddb2914317',
    messagingSenderId: '611184420790',
    projectId: 'inspection-wv',
    storageBucket: 'inspection-wv.firebasestorage.app',
    iosBundleId: 'com.example.inpectionUser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDY-MBGIoi-WAcEGVNjMo-K3O3KoN8jmcg",
    authDomain: "inspection-wv.firebaseapp.com",
    projectId: "inspection-wv",
    storageBucket: "inspection-wv.firebasestorage.app",
    messagingSenderId: "611184420790",
    appId: "1:611184420790:web:7ed67e37e32082f9914317",
    measurementId: "G-JFN2GF9V6Y",
  );
}
